version: 2

project_name: gofollower

before:
  hooks:
    - go mod tidy

builds:
  - env: [ CGO_ENABLED=0 ]
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
    id: linmac
    dir: .
    main: ./cmd/gofollower
    binary: follow

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: jksolbakken
    name: gofollower
  header: |
    ## gofollower ({{ .Version }})

brews:
  - repository:
      owner: jksolbakken
      name: homebrew-tap
      token: "{{ .Env.BREW_PUSH_TOKEN }}"
    name: gofollower
    homepage: "https://github.com/jksolbakken/gofollower"
    description: "Command-line utility for following HTTP links"
    directory: Formula
    install: |
      bin.install "follow"
    test: |
      assert_match version, shell_output("#{bin}/follow version")


